spring:
  application:
    name: mqq-ai-agent
  ai:
    dashscope:
      api-key: ${aliQwen-api}
      chat:
        options:
          model: qwen-plus
    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:8b
server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.mqq.agent.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
